//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHamburgueria.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using System.Web;
    using System.Runtime.Serialization;
    using System.ComponentModel;
    using System.Resources;

    public partial class Produto
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        //
        //[Range(10, 99999.99,
        //     ErrorMessage = "O Preço de Venda deve estar entre " +
        //                    "10,00 e 99999,99.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:C}")]
        //[DataType(DataType.Currency)]
        
        [Display(Name = "Preço")]
        public decimal Preco { get; set; }
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
        public string Ingredientes { get; set; }
        public byte[] Foto { get; set; }
        public string Tipo { get; set; }
    }
}
