//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHamburgueria.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using System.Web;

    public partial class Produto
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        [DataType(DataType.Currency)]
        public decimal Preco { get; set; }
        public string Descricao { get; set; }
        public string Ingredientes { get; set; }
        public byte[] Foto { get; set; }
        public string Tipo { get; set; }

        /*
        [DataType(DataType.Upload)]
        [Display(Name = "Imagem")]
        public HttpPostedFileBase ImageUpload { get; set; }
        */
    }
}
